### ISSUE TITLE
Cross-platform Outline links

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#57]
Outline links don't work from messaging apps because they break on the "|". The first part is opens the full outline, the second opens the current text. This is an issue for a text which is in the middle of a large outline. Users can't select the whole outline easily from most messenger apps.

Take for exemple O01JW00501JW15968 in Facebook Messenger:

https://www.tbrc.org/?locale=bo#!rid=O01JW005|O01JW00501JW15968$W22703

![f](https://user-images.githubusercontent.com/17675331/33609013-6d4584c2-da01-11e7-9828-488b6672fb7d.png)

In Wechat:
![ddd](https://user-images.githubusercontent.com/17675331/33608611-0a2047c0-da00-11e7-88ca-d7a651dee40c.png)

**Comment by subsystem7** [comment]
This is not a bdrc-lib-app issue.

I attempted to URLEncode the rid, and that link failed to load the outline node. This will require a server side change, perhaps honoring "-" as an "|" ??

original:
```
https://www.tbrc.org/?locale=bo#!rid=O01JW005|O01JW00501JW15968$W22703
```

url encoded:
```
https://www.tbrc.org/?locale=bo#!rid=O01JW005%7CO01JW00501JW15968%24W22703
```

**Comment by eroux** [comment]
It's not an app issue indeed, can you add it to the to do list ?

**Comment by jeffwallman** [comment]
We should resolve this asap.  I argue that

https://www.tbrc.org/link?RID=O01JW00501JW15968 should be supported from the GWT app

The issue is that the "|" |$" characters are not supported across the platforms our users use, including WeeChat and WhatsApp.  If we support deep linking using the Node RID, we will have cross-platform support.

Elie, can you comment on this?

**Comment by xristy** [comment]
I think one issue is recognizing that the RID is a Node RID and not an Outline RID. The “|” and “$” are part of the recognition.

Since these RIDs are in the mobile app payload they could be encoded differently and recognized in the app server. Maybe with “-“s.

Also there are sites such as ToL and Lotsawa that have the form of RIDs with “|” and “$”

Élie and I will discuss.

**Comment by jeffwallman** [comment]
The current form of the URL does not allow users on WeeChat and WhatsApp to share the links.  So I think we need to support another form of the URL that works on these platforms.  

NodeRID is unique in the database, and a simple look up will give you all the necessary information, including, the work, outline, start page and end page.  I do not think you need to build the recognition into the URL.  

I am not suggesting we erode support for the current URL.  But in the app, we need additional support for a new URL that doesn't break in the platforms our mobile users are using.

**Comment by xristy** [comment]
Élie and I are now together looking at the issue and it turns out that encoding the pipe, "|" via %7C and the dollar, "$" via %24 in the URL instead of using the pipe and dollar will form a complete URL in wechat and fb messenger etc.

The app server already handles the %7C and it is a simple change to the app server to handle the %24. 

If Asa makes the change from"|" to %7C and from "$" to %24 in the app. Then with the one line change in the app server all will work properly.

**Comment by xristy** [comment]
I've deployed an update to the app server to AWS and tested that the URL:

    https://www.tbrc.org/?locale=bo#!rid=O01JW005%7CO01JW00501JW15968%24W22703

works to open to the intended node of the outline.

Separately fb messenger and wechat have been verified to treat the above as a single URL.

When Asa tried the URL previously it failed to open to the intended node because of a deficiency in the app server. Now that has been corrected and once Asa changes the URLs to be encoded as discussed, then URLs should operate correctly in at least the tested mobile apps.

Currently I am unable to contact cn.bdrc.io either via ssh or http. I have no way of telling whether this is because connections are blocked or whether the server is down
