### ISSUE TITLE
Single author name not yet the right one

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#62]
The main name of P270 is listed correctly in the person view...

![f](https://user-images.githubusercontent.com/17675331/33612594-067ddf4e-da0d-11e7-9cc6-6dc2e788b96d.png)

...but not in the work view.

![f](https://user-images.githubusercontent.com/17675331/33612613-18bac442-da0d-11e7-83a2-74e71a4000f0.png)

The P270.json has the following:
"name":["ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་དབང་།","རྫོགས་ཆེན་མཁན་རབས ༠༥ ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","རྫོགས་ཆེན་དཔལ་དགེ་སྤྲུལ་སྐུ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","རྫ་དཔལ་སྤྲུལ།","དཔལ་སྤྲུལ་རིན་པོ་ཆེ།","དཔལ་སྤྲུལ་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","དཔལ་དགེ་སྤྲུལ་སྐུ།","ཁྱི་རྒན་དཔལ་དགེ","ཁྱི་རྒན་ཨ་བུ།","ཨ་བུ་ལྷོད་པོ།","ཨ་བུ་ཧྲལ་པོ།","རྫོགས་ཆེན་མཁན་རབས ༠༥","རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།"]}

The first one is the correct one.

**Comment by subsystem7** [comment]
This is because the Person is not loaded from the P270.json file, rather P270 is used to search the index, and the person name is the associated value. So, this can either be fixed by putting the correct name in the index, or by opening the P270.json file. The question for @eroux is, are each of the P270 name variants in the personIndex files?

**Comment by subsystem7** [comment]
actually... one sec. this is in the "browser" version. It is possible that I keep only one key. In the database driven version it would mean that I am simply taking the first result... which would mean that the first stored name would be displayed. @eroux please wait until I check this

**Comment by subsystem7** [comment]
ok, I am able to confirm that the author name that is displayed is the first author name with the rid P270 that is added to the database. Here is the import order:

![image](https://user-images.githubusercontent.com/1638461/33616702-a677819c-d9ab-11e7-90e3-7078b7b39ea7.png)

So basically we have two possible solutions.

1) make sure that the most important name comes first in the person index

This solution would be faster from the app user's perspective.

2) load the author json file and extract the 

This solution would require no change to the index files, but will result in a small delay when loading the author name whenever a work is viewed.


Please let me know what you want me to do. @eroux @jeffwallman @ngawangtrinley

**Comment by ngawangtrinley** [comment]
1. Or re-populate the personIndex-0.json file with the content of /persons/ so it matches its order.

**Comment by eroux** [comment]
that won't solve the issue, if you really want to solve it by changing the person index, then we have to completely change the person index. That's not a big change on my side, but we have to agree with Asa what the new format would be, run some tests, release 1.2, etc. We can do that. Asa, what would be best for you as a new format?

**Comment by subsystem7** [comment]
I think the best option is to include the best author name inside the work.json files along with the P numbers.

**Comment by eroux** [comment]
Asa, I'm not really sure what you mean, can you give an example?

**Comment by subsystem7** [comment]
for example W22084.json you would make the hasCreator array into an array of objects. In this example the key is P956 and the value is "སི་ཏུ་པཎ་ཆེན་ཆོས་ཀྱི་འབྱུང་གནས།" -- I would then extract the first element of the array and use this name. 

```
{
  "access": "open",
  "license": "publicdomain"
  "volumeMap": […]
  "outlinedBy": "O1GS12980",
  "publisherName": "དེལྷི་ཀརྨཔཨེ་ཆོདྷེཡ་གྱལྭཨེ་སུངྲབ་པརྟུན་ཁང་།"
  "hasCreator: [ { "P956":"སི་ཏུ་པཎ་ཆེན་ཆོས་ཀྱི་འབྱུང་གནས།"} ]  
  "publisherLocation: "དེལྷི།",
...
}
```

**Comment by eroux** [comment]
I see... Well, I'm quite reluctant to the idea of doing that, for a few reasons:

- looking at the code, that's not a small change, so I won't be able to do that before Monday possibly
- it duplicates data and makes the payload bigger (maybe not in a very significant way, but it should be visible)
- I just don't like the idea, but that's not a rational argument

there's no blocking issue here, just some time needed before I can do that if we decide to go in that direction.

**Comment by xristy** [comment]
I'm confused. Why not just use the person key, `P270`, from the Work `hasCreator` field to open the `P270.json` and simply retrieve the first name  from the `name` field? Maybe a separate _preferred name_ table with a single name in it since the data in the json payload has the correct order.

**Comment by subsystem7** [comment]
As I noted above, @xristy and @eroux, loading the P270.json file would require no change to the index files, but will result in a small delay when loading the author name whenever a work is viewed (for slower phones).

For performance, having the "preferred" name in the work json file makes sense or loading a preferred name index.  It does increase the "payload" -- but, not by much. In this case, I believe that how the user feels when using the app is more important than data normalization. In the future, we will have a more sophisticated database, and I'll be able to simply grab the preferred name through a relationship rather than disk access. 

In order of effort on my part from least to most:

 1) add name to work json file
 2) load person file and take the first name
 3) load a new preferred person index, create a new table

My strong preference is 1 or 2, otherwise I would have already built #2.

**Comment by eroux** [comment]
Fine, I'll try to do have that done on Monday

**Comment by eroux** [comment]
a new dataset has been generated. I'm a bit puzzled by the main title in the person view, does it come from the search or does it have the same sort of problem?

**Comment by ngawangtrinley** [comment]
@eroux the main title in the orange bar is indeed the keyword that was searched. Since the current order in the personIndex-0.json is random, I still think that the easiest solution would be to run a post-processing script that would make sure the first instance of each RID is the one with the preferred name. Something like finding the instance with the preferred name for each RID and moving it on top of the stack...
