### ISSUE TITLE
Display Deep Nodes Correctly

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#81]
Parts aren't listed in collections that have collections, but are listed in texts contained within the collections...

Parts of collections are replaced by an `x` ... Or is it something else? Here I'm expecting to see the Parts section as it appears in Tap 2 (see below).

![](https://user-images.githubusercontent.com/17675331/116957068-7e29ba80-acc9-11eb-841d-4e0cd2d22282.png)

Here's my parts story:

## Tap 1

I search for གདུལ་བ་གཞི་ the first text, in the first section of the above collection. I guess it's the first hit and tap on it.

![](https://user-images.githubusercontent.com/17675331/116957184-cfd24500-acc9-11eb-960f-0d3ef45499ef.png)

## Tap 2

The text info appears and weirdly enough the parts of the main collection appear too! I tap on འདུལ་བ་ (MW26071\_S0001) the section containing my text (MW26071\_0001) ...

![](https://user-images.githubusercontent.com/17675331/116957432-6ef73c80-acca-11eb-98db-0ca691471666.png)

## Tap 3

The section info appears and my text (MW26071\_0001) is listed as the first part of the section (MW26071\_S0001), as expected.

![](https://user-images.githubusercontent.com/17675331/116957574-c3022100-acca-11eb-946a-1a9b02db6443.png)

## Tap 4

When taping on the text title, I get the text info without the Parts I got in Tap 2.

![](https://user-images.githubusercontent.com/17675331/116957630-e7f69400-acca-11eb-8785-345dfd56bc08.png)

**Comment by subsystem7** [comment]
Hi @ngawangtrinley and @eroux I do not understand why 
**MW26071_0001** is a work part of **MW26071_S0001** which is a part of **MW26071_0001**. This seems like a circular reference. Either way, the reason that the node at the end here has no parts is because it actually has no parts in the index files.  Maybe you guys can help me understand the data here, and maybe this is simply a limitation of the current index file specification?

![image](https://user-images.githubusercontent.com/1638461/117661734-bec38100-b16c-11eb-8731-01296ce6d4bc.png)

![image](https://user-images.githubusercontent.com/1638461/117661818-d995f580-b16c-11eb-997b-df9b8761066c.png)

**Comment by eroux** [comment]
@subsystem7 I'm looking at `03.json` and I can see that `MW26071_0001` is a part of `MW26071_S0001` as indicated here:

```json
{
      "t": [
        "འདུལ་བ།"
      ],
      "id": "MW26071_S0001",
      "n": [
        {
          "t": [
            "འདུལ་བ་གཞི།"
          ],
          "id": "MW26071_0001"
        },
```

but I can't find an indication that `MW26071_S0001` is a part of `MW26071_0001`. Where did you find that information?

**Comment by eroux** [comment]
might be linked to https://github.com/buda-base/BDRC-Lib-App/issues/89

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/119517219-6d5aea80-bd45-11eb-9bfa-74ca120ed0d1.png)


This should link to a node that is two levels in. Need to create a method for getting to the proper node, and also providing navigation to the parent node.

**Comment by eroux** [comment]
@subsystem7 `MW23703_4464` is a good example of something that's at the end of a very big tree
