### ISSUE TITLE
“Print Type” in metadata for texts

### ISSUE THREAD

**Issue by JannTibetan** [BuddhistDigitalResourceCenter/BDRC-Lib-App#92]
Perhaps we don't need this rubric for the mobile app. 
![image](https://user-images.githubusercontent.com/44705185/118710937-f5447000-b7ec-11eb-8a35-18a349559ccc.jpeg)

**Comment by subsystem7** [comment]
@JannTibetan  already made the change to map the print type in all three languages, please see: https://github.com/buda-base/BDRC-Lib-App/issues/85

**Comment by eroux** [comment]
to give a bit more context: the print type is in the data because initially the app was supposed to help the people on the field looking if we already had the books they were looking at without the need to go online. So if they see a xylo and we only have a manuscript or mondern print they would know it's interesting. It seems this is not really the main use case anymore, but I'm thinking it could still be a relevant?
